### ISSUE TITLE
Ingestion process fails in islandora when attempting to assign handle to zip file of book pages where no MODS file is included

### ISSUE THREAD

**Issue by HomerITS** [discoverygarden/islandora_handle#3]
A routine in the handle.module to handle an edge case, in this case a zip file of book pages without a MODS file being ingested using the book ingestion service, fails while making a call to an undefined function [ islandora_delete_handle() ].

The following error is thrown and the ingestion process terminates.
PHP Fatal error:  Call
to undefined function islandora_delete_handle() in
/var/www/html/drupal7/sites/all/modules/islandora_handle-7.x/islandora_handle.module
on line 80.

**Comment by willtp87** [comment]
https://github.com/discoverygarden/islandora_handle/pull/4 should fix this.

**Comment by jonathangreen** [comment]
I'm going to make this as closed.  Let me know if its still an issue HomerITS.
